#!/usr/bin/bash
NIRI_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/niri/config.kdl"
DYNAMIC_NIRIUSH_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/niri/niriush.kdl"

usage() {
    cat <<EOF
Usage: $0 COMMAND [OPTIONS]... ARGUMENTS
Manage niri windows.
Commands:
  addconf STRING              Add STRING (if not found) to the dynamic niriush configuration file.
  rmconf STRING               Remove STRING (if found) from the dynamic niriush configuration file.
  sedconf SED_ARGS...         Modify the dynamic niriush configuration file using SED_ARGS.
  resetconf                   Reset the dynamic niriush configuration file to default state.
  windo [OPTIONS]... ACTION   Perform ACTION on windows matching selection criteria.
  fetch [OPTIONS]...          Pulls matching windows to focused or specified workspace.
  scatter [OPTION]            Move each matching windows to its own workspace.
  help                        Show this help message and exit.
Options for 'windo':
  --filter JQ_FILTER          Apply a custom jq filter to select windows.
  --appid APP_ID              Select windows by application ID regex (case insensitive).
  --title TITLE               Select windows by title regex (case insensitive).
  --workspace REFERENCE       Select windows by workspace index, name, or 'focused'.
  --id-flag FLAG              Specify the flag to use for specifying window IDs in ACTION (default: --id).
  --extra-args ARGS           Additional arguments to pass to ACTION.
Options for 'fetch':
  --target-workspace-idx IDX  Index of the workspace to fetch windows to (default: focused workspace).
  --tile                      Tile fetched windows on the focused workspace after fetching (experimental).
Option for 'scatter':
  --down                      Direction to scatter windows, default is up
General Options:
  --help, -h                  Show this help message and exit.
EOF
    exit "$1"
}

# niriu.sh is called primarily with no terminal, so desktop notifications for errors.
error() {
    local error_message="Error: ${BASH_SOURCE[0]} failed in line ${BASH_LINENO[0]}"
    local error_line
    error_line="${1:-"$(sed -n "${BASH_LINENO[0]}"p "${BASH_SOURCE[0]}")"}"
    if [ -t 2 ]; then
        echo -e "$error_message\n$error_line" >&2
    else
        notify-send -a niriush -u critical "$error_message" "$error_line"
    fi
    exit 1
}
trap error ERR
set -E

addconf() {
    grep -Fq "$1" "$DYNAMIC_NIRIUSH_CONFIG_FILE" && return 0
    echo "$1" >> "$DYNAMIC_NIRIUSH_CONFIG_FILE"
    niri msg action load-config-file
}

rmconf() {
    grep -Fq "$1" "$DYNAMIC_NIRIUSH_CONFIG_FILE" || return 0
    sed -ie "/$1/d" "$DYNAMIC_NIRIUSH_CONFIG_FILE"
    niri msg action load-config-file
}

sedconf() {
    sed -ie "$@" "$DYNAMIC_NIRIUSH_CONFIG_FILE"
    niri msg action load-config-file
}

resetconf() {
    echo "// Dynamically generated by niriu.sh" > "$DYNAMIC_NIRIUSH_CONFIG_FILE"
    niri msg action load-config-file
    if ! grep -Fq 'include "niriush.kdl"' "$NIRI_CONFIG_FILE"; then
        [ -t 0 ] || error "Please include $DYNAMIC_NIRIUSH_CONFIG_FILE in $NIRI_CONFIG_FILE"
        echo "$DYNAMIC_NIRIUSH_CONFIG_FILE is not included in $NIRI_CONFIG_FILE" >&2
        read -rp "Include it now? [y/N] " response
        [[ "$response" =~ ^[Yy]$ ]] || error "User declined to include dynamic config file"
        echo "include \"$DYNAMIC_NIRIUSH_CONFIG_FILE\"" >> "$NIRI_CONFIG_FILE"
        niri msg action load-config-file
    fi
}

get() {
    local object_type="$1"
    shift
    local property="$1"
    shift
    local filter='.[]'
    while [ $# -gt 0 ]; do
        filter="$filter | select($1)"
        shift
    done
    niri msg --json "$object_type" | jq -r "$filter | .$property"
}

windo() {
    local window_ids="$1"
    shift
    local window_id_flag="$1"
    shift
    local extra_args="$1"
    shift
    # shellcheck disable=SC2046,SC2086  # We want word splitting on extra_args.
    xargs -I{} niri msg action "$@" $extra_args "$window_id_flag" {} <<<"$window_ids"
}

fetch() {
    local window_ids="$1"
    local workspace_idx="$2"
    local current_window_id
    current_window_id=$(get windows id '.is_focused == true')
    niri msg action focus-workspace "$workspace_idx"
    # Can't use `windo` here because workspace idx is relative and may change after moving each window.
    for window_id in $window_ids; do
        local current_workspace_idx
        current_workspace_idx="$(get workspaces idx '.is_focused == true')"
        niri msg action move-window-to-workspace "$current_workspace_idx" --window-id "$window_id"
    done
    niri msg action focus-window --id "$current_window_id"
}

optimal_grid_layout() {
    local width=$1
    local height=$2
    local elements=$3
    local aspect_ratio
    local rows
    local columns
    aspect_ratio=$(bc <<< "scale=2; $width / $height")
    rows=$(bc <<< "scale=0; sqrt($elements * $aspect_ratio)/1")
    if [ "$rows" -eq 0 ]; then
        rows=1
    fi
    columns=$(bc <<< "($elements + $rows - 1) / $rows")
    echo "$rows $columns"
}

tile() {
    local window_ids="$1"
    local workspace_idx="$2"
    local width
    local height
    local rows
    local columns
    read -r width height < <( \
        niri msg --json focused-output | jq -r '.logical | "\(.width) \(.height)"')
    read -r rows columns < <(optimal_grid_layout "$width" "$height" "$(wc -l <<<"$window_ids")")

    local current_window_id
    current_window_id=$(get windows id '.is_focused == true')
    niri msg action focus-workspace "$workspace_idx"
    niri msg action focus-column-first
    for ((column = 0; column < columns; column++)); do
        echo "Column $column/$columns"
        for ((row = 1; row < rows; row++)); do
            niri msg action consume-window-into-column
        done
        niri msg action focus-column-right
    done
    cell_width=$((width / columns))
    windo "$window_ids" '--id' '' set-window-width "$cell_width"
    niri msg action focus-window --id "$current_window_id"
}

scatter() {
    local window_ids="$1"
    local target_workspace_idx="${2:-0}"
    local current_window_id
    current_window_id=$(get windows id '.is_focused == true')
    windo "$window_ids" '--window-id' '--focus false' move-window-to-workspace "$target_workspace_idx"
    niri msg action focus-window --id "$current_window_id"
}

niriush() {
    local command_name="$1"
    shift
    case "$command_name" in
        ''|help|--help|-h) usage 0;;
        resetconf)
            [ $# -gt 0 ] && usage 1
            resetconf
            exit
            ;;
        addconf|rmconf)
            [ $# -gt 1 ] && usage 1
            ;&
        sedconf)
            [ $# -lt 1 ] && usage 1
            $command_name "$@"
            exit
            ;;
        windo|fetch|scatter)
            local window_ids
            local action=()
            local filters=()
            local windo_id_flag=--id
            local windo_extra_args
            local target_workspace_idx
            local tile
            while [ $# -gt 0 ]; do
                case "$1" in
                    --filter)
                        shift
                        filters+=("$1")
                        shift
                        ;;
                    --appid)
                        shift
                        filters+=(".app_id | test(\"$1\"; \"i\")")
                        shift
                        ;;
                    --title)
                        shift
                        filters+=(".title | test(\"$1\"; \"i\")")
                        shift
                        ;;
                    --workspace)
                        shift
                        local workspace_id
                        if [ "$1" = "focused" ]; then
                            workspace_id=$(get workspaces id '.is_focused == true')
                        else
                            workspace_id=$(get workspaces id ".idx == $1")
                        fi
                        filters+=(".workspace_id == $workspace_id")
                        shift
                        ;;
                    --id-flag)
                        [ "$command_name" != "windo" ] && usage 1
                        shift
                        windo_id_flag="$1"
                        shift
                        ;;
                    --extra-args)
                        [ "$command_name" != "windo" ] && usage 1
                        shift
                        windo_extra_args="$1"
                        shift
                        ;;
                    --down)
                        [ "$command_name" != "scatter" ] && usage 1
                        target_workspace_idx=255
                        shift
                        ;;
                    --target-workspace-idx)
                        [ "$command_name" != "fetch" ] && usage 1
                        shift
                        target_workspace_idx="$1"
                        shift
                        ;;
                    --tile)
                        [ "$command_name" != "fetch" ] && usage 1
                        tile=true
                        shift
                        ;;
                    *)
                        [ "$command_name" != "windo" ] && usage 1
                        action+=("$1")
                        shift
                        ;;
                esac
            done
            window_ids="$(get windows id "${filters[@]}")"
            case $command_name in
                windo) windo "$window_ids" "$windo_id_flag" "$windo_extra_args" "${action[@]}";;
                scatter) scatter "$window_ids" "$target_workspace_idx";;
                fetch)
                    [ "$target_workspace_idx" ] || \
                        target_workspace_idx=$(get workspaces idx '.is_focused == true')
                    scatter "$window_ids"
                    fetch "$window_ids" "$target_workspace_idx"
                    if [ "$tile" = true ]; then
                        tile "$window_ids" "$target_workspace_idx"
                    fi
                    ;;
            esac
        ;;
        *) echo "Unknown command: $command_name"; usage 1;;
    esac
}

niriush "$@"
